networks:
  proxy-tier:
    driver: bridge

services:
  # 1. Torre de Control de Red (NPM)
  # Se encargará de redirigir el tráfico de Streamlit hacia la IP física de proc-gpu-01
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: web_commander
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
    networks:
      - proxy-tier

  # 2. Telemetría SQL Directa
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma_panel
    restart: always
    environment:
      - PMA_HOST=192.168.56.10
      - PMA_PORT=3306
      - PMA_USER=pipeline_user
      - PMA_PASSWORD=pipeline_password
    networks:
      - proxy-tier

  # 3. Panel CRUD y Análisis de Datos
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: data_crud_panel
    restart: always
    volumes:
      - ./appsmith_data:/appsmith-stacks
    networks:
      - proxy-tier
